### Task list
1. Markdown and code cells
1. importing packages
1. numpy arrays
1. loops, indentation (colon **:**), ifs
1. print
1. functions
1. help

In [1]:
import numpy as np

### Creating arrays

In [2]:
# creating arrays
x = np.linspace(0, 9, 10) # args = start, stop, number
y = np.arange(0, 10, 1.0) # args = start, stop, step
z = np.zeros(10)
for i in range(10):
    z[i] = i

In [3]:
print(x)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [4]:
print(y)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [5]:
print(z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


### Functions

In [6]:
# function that returns square
def calc_square(x):
    return x**2

In [7]:
calc_square(3)

9

In [8]:
calc_square(z)

array([ 0.,  1.,  4.,  9., 16., 25., 36., 49., 64., 81.])